---
server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: ${CONTEXT_PATH:/config-server} 
  
#Basic Authentication Set Up Spring Security
spring:
  security:
    user:
      name: admin
      password: password
#For Distributed Tracing using Spring Cloud Sleuth
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
    com.microservice: DEBUG