---
#Development landscape configurations
spring:
  profiles: development
  security: #Basic Authentication Set Up Spring Security for config server
    user:
      name: admin
      password: password
server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: ${CONTEXT_PATH:/config-server} 
#Eureka Service registry Configuration        
eureka:
  client:    
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      # The default 'instance id' won't be unique if running on the same host and using 'server.port=0'
      # By Default, The default application name (that is, the service ID), 
      # are ${spring.application.name}, and ${server.port}, respectively and is suffice for production
      instance-id: ${spring.application.name}:${random.int[1,99]}
      hostname: localhost
#For Distributed Tracing using Spring Cloud Sleuth
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: INFO
    com.microservice: DEBUG
#Actuator Endpoint config    
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
#Staging landscape configurations
spring:
  profiles: staging
  security:
    user:
      name: adminQA
      password: passwordQA
server:
  port: ${SERVER_PORT:16789}
  servlet:
    context-path: ${CONTEXT_PATH:/config-server}       
eureka:
  client:    
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_STAGING}
  instance:      
      hostname: localhost
logging:
  level:
    root: ERROR
    org.springframework.cloud.sleuth: ERROR
    com.microservice: ERROR
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
#Production landscape configurations
spring:
  profiles: production
  security:
    user:
      name: ${AUTH_USERNAME_PRODUCTION}
      password: ${AUTH_PASSWORD_PRODUCTION}
server:
  port: ${SERVER_PORT:16789}
  servlet:
    context-path: ${CONTEXT_PATH:/config-server}     
eureka:
  client:    
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_PRODUCTION}
  instance:      
      hostname: localhost
logging:
  level:
    root: ERROR
    org.springframework.cloud.sleuth: ERROR
    com.microservice: ERROR   
management:
  endpoints:
    web:
      exposure:
        include: info, health