#Profile specific landscape configurations with placeholders
spring:   
  security: #Basic Authentication Set Up Spring Security for config server
    user:
      name: configServerUser
      password: ${CONFIG_SERVER_USER_PASSWORD:GbVx74Gp6cmEQnUcyNQKcCVu5NUfpx5K}
server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: ${CONTEXT_PATH:/config-server}
#Eureka Service registry Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eurekaServerUser:${EUREKA_SERVER_USER_PASSWORD:GbVx74Gp6cmEQnUcyNQKcCVu5NUfpx5K}@${EUREKA_HOST:toll-platform-discovery-service}:9091/eureka/}
       #toll-platform-discovery-service is DNS name(hostname) for container and for the same host file entry on windows is also needed.
  instance:
      # The default 'instance id' won't be unique if running on the same host and using 'server.port=0'
      # By Default, The default application name (that is, the service ID), 
      # are ${spring.application.name}, and ${server.port}, respectively and is suffice for production
      instance-id: ${spring.application.name}:${random.value}
      preferIpAddress: true
#For Distributed Tracing using Spring Cloud Sleuth and log level config
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.cloud.sleuth: ${LOG_LEVEL:ERROR}
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.boot.devtools: WARN
    com.microservice: ${LOG_LEVEL:INFO}
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
#Actuator Endpoint config
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,hystrix.stream}